language: android
android:
  components:
    - echo y | android update sdk -u -a -t tools
    - echo y | android update sdk -u -a -t platform-tools
    - echo y | android update sdk -u -a -t build-tools-26.0.1
    - echo y | android update sdk -u -a -t android-26
    - echo y | android update sdk -u -a -t extra-google-m2repository
    - echo y | android update sdk -u -a -t extra-android-m2repository # for design library
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'intel-android-extra-license.+'
 
before_install:
  - chmod +x gradlew

script:
   - ./gradlew build connectedCheck
